### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by eth4ever** [agiliway/com.agiliway.civimobileapi#8]
Civimobileapi looks very promising. Thanks for the great work.

Login from the iOS app fails: "Unknown error"
Logs in Drupal show: "Page not found" on this url: 
/sites/all/modules/civicrm/extern/rest.php?key=<key>&civimobile=1&api_key=<api_key>&entity=CiviMobileSystem&action=get&json=%7B%22sequential%22:1,%22return%22:%22cms,crm_version,ext_version%22,%22options%22:%7B%22limit%22:0%7D%7D'

We are on civicrm 4.7 / Drupal 7

**Comment by AWG-Bohdan** [comment]
Hi Erik,

Thank you for your interest in the CiviMobile App. 
Could you check that you have done everything correctly:
   • installed correct CiviMobileApi extension https://github.com/agiliway/com.agiliway.civimobileapi
   • If you installed CiviCRM in subfolder than the domain URL for login should be the same as you are using in a web browser. (Ex: http://your-domain.com/  - http://your-domain.com )

If you still can’t log in please provide us with simple user account credentials. The user has to have “CiviMobile access” and “View my profile” permissions. 

Regards

**Comment by eth4ever** [comment]
Hello Bohdan,

Thanks for your message. Yes, I followed all the necesarry steps (nothing much different than for other extensions). I do use civimobileapi on a sub-domain. To login from tha mobile app I use this domain htpps://[my sub-domain].[my domain].nl
The app does work on an other instance (same domain, different sub-domain). But this is Civi version 5.11.

You wrote:
>  The user has to have “CiviMobile access”
Where do I give a user "CiviMobile access?

**Comment by AWG-Bohdan** [comment]
Let continue discussion by email civicrm@agiliway.com

**Comment by savionlee** [comment]
I believe I have this same issue that eth4ever is describing.

I too have a subdomained Wordpress CMS site. I have followed all the steps in the youtube video again with the latest version of CiviCRM release and I can't get the mobile app to authenticate due to an unknown error. 

I was carrying an authentication token back when it worked with CiviCRM version 5.12, CiviMobile version 2.0, and CiviMobileAPIFix 1.0. I upgraded civimobile and my authentication was working still, with a few minor bugs. I upgraded CiviCRM last week or two, still working on the phone due to old authentication token. Then I signed out of my phone today and I can't sign back in. On my other devices last week I tried to setup civimobile app on and I kept getting an unknown error. I thought it was due to the number of sessions in use so i didn't think much about it.

I've tried reverting civimobile extension down to 3.0 and 2.0, and a different version of the mobile app with the current version of CiviCRM. both did not work.

I found a fix and **was able to login** by reverting CiviCRM down to 5.12 and CiviMobile Extension 2.0 with CiviMobile application on 2.1.1

**Comment by Upperholme** [comment]
I'm getting the same 'Unknown error' message when trying to connect to a Wordpress 5.2/CiviCRM 5.9.0 install. I have installed and activated the Wordpress plugin. I have installed the extension (version 3.1) and I'm trying to connect using the iOS mobile app. The app can connect to the demo site, but gives the error when trying to connect to my site. Double checked all the settings. Can't see anything in the CiviCRM log file.

**Comment by andriystabryn** [comment]
Hi @Upperholme ,
Did you install https://github.com/agiliway/com.agiliway.civimobileapi and https://github.com/agiliway/com.agiliway.civicrmapifixforwordpress ?
Can you send me more details andriy.stabryn@agiliway.com (I need domain name)?

**Comment by Upperholme** [comment]
Hi. Yes - both plugin and extension are installed. The domain name is https://www.rotherhamfederation.org

**Comment by andriystabryn** [comment]
I've found a bug in WP authentication, thanks for helping!
We are going to release a new app with fix tomorrow, so you will be able to download it within 2-3 days.
 
Thanks, again!

**Comment by savionlee** [comment]
Awesome! Thanks @andriystabryn ! 🎉

**Comment by eth4ever** [comment]
Great. I'll go end test it. Thanks @andriystabryn

**Comment by andriystabryn** [comment]
@eth4ever @savionlee @Upperholme We have released 3.1 version of application.
Can you try to install extension 3.1 and application 3.1 version and test again?

**Comment by savionlee** [comment]
@andriystabryn 

I no longer get stuck at authentication. 

BUT, after the authentication process, I am told there is a server API error and asked to send it into the team for support. I've selected yes to the prompt. I don't know where to find the local copy of the api error.

**Comment by eth4ever** [comment]
I re-installed the extension 3.1 and updated the iOS app. But I still get the same error as mentioned by @savionlee.
I'm on Drupal 7.59 and Civi 5.0
Thanks for all the great work. Hope we can fix it.

**Comment by andriystabryn** [comment]
@savionlee and @eth4ever  can you share your domains name?
I want to find crash logs in our system, but I need your domain to identify your problems.
You can send me to andriy.stabryn@agiliway.com and leave here.

Thanks!

**Comment by Upperholme** [comment]
I already had version 3.1 of the extension installed. The WP plugin is at version 1.0. My iOS app is updated to version 3.1. I still get the 'Unknown Error' when trying to login.

**Comment by savionlee** [comment]
@andriystabryn sent you an email, prefer not to leave it on the issue thread.

**Comment by Upperholme** [comment]
With the new iOS app I can continue to login to a Drupal 7/Civi 5.13.4 site with no problem.

**Comment by Upperholme** [comment]
Wondering if there's been any progress on this issue. Keen to be able to use the mobile app with Wordpress sites.

**Comment by savionlee** [comment]
In an email with Andy, he confirmed a suspicion of mine.

The CiviMobileAPI WordPress fix needs to be updated to match the latest API
changes in CiviCRM and CiviMobileAPI.

I didn't get a timeline. Would be nice to use the app again.

Savion

**Comment by andriystabryn** [comment]
Hi everyone,
Sorry for the long response.
Currently we are investigation how to resolve the problem. We are planning to release the fix and new version of extension and application within few days.

**Comment by eth4ever** [comment]
I downloaded the new version 3.2 login is fine now. Als for civi 5.0. Thanks.

**Comment by adam-devapp** [comment]
Still getting an API error message on 3.2 using WP, CiviCRM 5.13.5, and the WP URL fix module.

**Comment by Upperholme** [comment]
Updated a WP site to use version 3.2 of the extension. Plugin remains at v 1.0.0. Cleared the caches. iOS mobile app now reports: "Can't connect to the server. Check the website URL or internet connection."

**Comment by andriystabryn** [comment]
@adam-devapp and @Upperholme we have released new version (3.2.1). It should works with https://github.com/mecachisenros/civicrm-wp-rest plugin. Could you try to install this plugin (and remove our CiviMobileAPIFix plugin) ?

**Comment by andriystabryn** [comment]
@savionlee should help to fix your problem also!

**Comment by Upperholme** [comment]
OK, the WP plugin https://github.com/mecachisenros/civicrm-wp-rest states it needs PHP 7.1, and my server is not there yet. We're still working on that, and once I have it in place I'll test and report back.

**Comment by AWG-Bohdan** [comment]
Hello,

We have moved the project space for CiviMobileaAPI to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/civimobileapi

All issues have been migrated to: https://lab.civicrm.org/extensions/civimobileapi/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
